apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ilab-test03-gitops
  description: This is GitOps manifest for ilab-test03   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: ilab-test03
    janus-idp.io/tekton: ilab-test03 
    backstage.io/kubernetes-id: ilab-test03 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ilab-test03
