apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ilab-test03
  janus-idp.io/tekton: ilab-test03
  backstage.io/kubernetes-id: ilab-test03
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ilab-test03
resources: 
- initialize-namespace.yaml
- deployment.yaml
- route.yaml
- service.yaml
